trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
    configFilePath: './GitVersion.yml'

- task: Docker@2
  inputs:
    containerRegistry: 'Dockerhub'
    repository: 'flyingpianoman/proxy-vpn-proxy'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: |
      $(GitVersion.NugetVersion)
      latest
