version: '3.4'

services:
  proxy-vpn-proxy:
    container_name: proxy-vpn-proxy
    cap_add:
      - NET_ADMIN
    dns:
      - 209.222.18.222
      - 209.222.18.218
    volumes:
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/net/tun:/dev/net/tun
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - OPENVPN_CONFIG=
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - VPN_CONNECTION_PROXY_ADDRESS=
      - VPN_CONNECTION_PROXY_PORT=
    volumes:
      - ./config:/config
    ports:
      - 8888:8888